Upgrade to latest version of mocha
This fixes an error that suddenly started appearing on travis builds
today:

    Error: global leak detected: documents

I'm not sure why upgrading fixes it, but all of the tests still
pass so it doesn't seem to have any negative consequences.